# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceMaskDetector.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1342, 709)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 661, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.videoframe = QtWidgets.QLabel(self.centralwidget)
        self.videoframe.setGeometry(QtCore.QRect(20, 90, 1041, 591))
        self.videoframe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.videoframe.setText("")
        self.videoframe.setAlignment(QtCore.Qt.AlignCenter)
        self.videoframe.setObjectName("videoframe")
        self.control_btn = QtWidgets.QPushButton(self.centralwidget)
        self.control_btn.setGeometry(QtCore.QRect(1130, 580, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.control_btn.setFont(font)
        self.control_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.control_btn.setObjectName("control_btn")
        self.browse_btn = QtWidgets.QPushButton(self.centralwidget)
        self.browse_btn.setGeometry(QtCore.QRect(1130, 460, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.browse_btn.setFont(font)
        self.browse_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.browse_btn.setObjectName("browse_btn")
        self.file_path = QtWidgets.QLineEdit(self.centralwidget)
        self.file_path.setGeometry(QtCore.QRect(1080, 520, 241, 31))
        self.file_path.setObjectName("file_path")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1140, 210, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.alert_msg = QtWidgets.QTextBrowser(self.centralwidget)
        self.alert_msg.setGeometry(QtCore.QRect(1070, 240, 256, 192))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.alert_msg.setFont(font)
        self.alert_msg.setObjectName("alert_msg")
        self.datetime = QtWidgets.QLineEdit(self.centralwidget)
        self.datetime.setGeometry(QtCore.QRect(1070, 160, 251, 31))
        self.datetime.setObjectName("datetime")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1140, 120, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1342, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Face Mask Detection and Alert Message"))
        self.control_btn.setText(_translate("MainWindow", "OPEN CAMERA"))
        self.browse_btn.setText(_translate("MainWindow", "BROWSE FILE"))
        self.label_2.setText(_translate("MainWindow", "Alert Message"))
        self.label_3.setText(_translate("MainWindow", "Date & Time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
